//internal dependencies
import TopMenu from "@/containers/Menus/TopMenu/TopMenu";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
        <TopMenu/>
        {children}
      </>
  )
}
